import Layout from "../components/Layout";

function Home() {
  return (
    <Layout title="Home page">
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
      <h1>Homepage</h1>
    </Layout>
  );
}

export default Home;
